export interface ApplicantInfo {
  name: string;
  email: string;
  number: string;
  college?: string;
  program: string;
  message?: string;
}

export function getHRNotificationTemplate(info: ApplicantInfo): string {
  const collegeVal = info.college ? info.college : 'Not Provided';
  const messageVal = info.message ? info.message : 'No message';

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New Internship Application</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      background-color: #f9fafb;
      color: #111827;
      margin: 0;
      padding: 0;
    }
    .wrapper {
      width: 100%;
      background-color: #f3f4f6;
      padding: 40px 20px;
      box-sizing: border-box;
    }
    .container {
      max-width: 600px;
      margin: 0 auto;
      background: #ffffff;
      border: 1px solid #e5e7eb;
      border-radius: 12px;
      overflow: hidden;
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
    }
    .header {
      background-color: #1f2937;
      padding: 30px;
      color: #ffffff;
    }
    .header h2 {
      margin: 0;
      font-size: 20px;
      font-weight: 700;
    }
    .header p {
      margin: 5px 0 0 0;
      font-size: 13px;
      color: #9ca3af;
    }
    .content {
      padding: 30px;
    }
    .details-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 24px;
    }
    .details-table th, .details-table td {
      padding: 12px 16px;
      text-align: left;
      font-size: 14px;
      border-bottom: 1px solid #f3f4f6;
    }
    .details-table th {
      background-color: #f9fafb;
      color: #4b5563;
      font-weight: 600;
      width: 35%;
    }
    .details-table td {
      color: #111827;
      font-weight: 500;
    }
    .message-box {
      background-color: #f9fafb;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 16px;
      font-size: 14px;
      color: #374151;
      line-height: 1.6;
      white-space: pre-wrap;
    }
    .footer {
      padding: 20px 30px;
      background-color: #f9fafb;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      font-size: 12px;
      color: #6b7280;
    }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="container">
      <div class="header">
        <h2>New Internship Application Received</h2>
        <p>A new user has submitted the internship form on DCT website.</p>
      </div>
      <div class="content">
        <table class="details-table">
          <tr>
            <th>Applicant Name</th>
            <td>${info.name}</td>
          </tr>
          <tr>
            <th>Email Address</th>
            <td><a href="mailto:${info.email}">${info.email}</a></td>
          </tr>
          <tr>
            <th>Phone Number</th>
            <td><a href="tel:${info.number}">${info.number}</a></td>
          </tr>
          <tr>
            <th>College / Inst.</th>
            <td>${collegeVal}</td>
          </tr>
          <tr>
            <th>Program Slug</th>
            <td><strong>${info.program}</strong></td>
          </tr>
        </table>

        <h3 style="font-size: 14px; font-weight: 600; color: #4b5563; margin-top: 0; margin-bottom: 8px;">Applicant Message / Cover Note:</h3>
        <div class="message-box">${messageVal}</div>
      </div>
      <div class="footer">
        <p>This email was automatically generated by the DCT Internship website portal.</p>
      </div>
    </div>
  </div>
</body>
</html>`;
}
